### ISSUE TITLE
opencv error

### ISSUE THREAD

**Issue by bhyzhao** [hpc203/yolov5-dnn-cpp-python-v2#1]
I have problem of loading onnx model by opencv.  How to fix it? Thx.
pytorch 1.7.1
opencv 4.3.0
Here is the detail:
>>>python main_yolov5.py --net_type yolov5s
Traceback (most recent call last):
  File "main_yolov5.py", line 110, in <module>
    yolonet = yolov5(args.net_type, confThreshold=args.confThreshold, nmsThreshold=args.nmsThreshold, objThreshold=args.objThreshold)
  File "main_yolov5.py", line 21, in __init__
    self.net = cv2.dnn.readNet(yolo_type + '.onnx')

cv2.error: OpenCV(4.3.0) /io/opencv/modules/dnn/src/graph_simplifier.cpp:79: error: (-212:Parsing error) Input node with name 925 not found in function 'getInputNodeId'

**Comment by xuwei1119** [comment]
try opencv4.5.1
